[tool.black]
line-length = 79
skip-string-normalization = true
force-exclude = '''
(
    ^/tests
    | ^/venv
)
'''

[tool.isort]
profile = "black"
src_paths = ["./blogicum"]
extend_skip_glob = ["tests/*"]

[tool.pyright]
venvPath = '.'
venv = 'venv'

